---
abstract: 'URI/Path::Class combination'
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Lazy: '0.03'
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Path-Resource
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0
  Path::Abstract: 0
  Path::Class: 0
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/robertkrimen/path-resource/tree/master
version: '0.072'
